name: deploy-app-to-gh-pages
env:
  PUBLISH_DIR: blazor.wasm.ghpages/bin/Release/netstandard2.1/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Unit Tests
      run: dotnet test

    - name: Publish app
      run: dotnet publish -c Release

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /blazor-sandbox/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
